name: Docker Container
on:
  workflow_dispatch:
  push:
    branches: ["main"]
    # Publish semver tags as releases.
    tags: ["v*.*.*"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    uses: riesinger/github-workflows/.github/workflows/build-docker.yml@main
    with:
      image-name: plausible-exporter
      platforms: linux/amd64,linux/arm/v7,linux/arm64
    secrets: inherit
